# This is a basic workflow to help you get started with Actions

name: build-node-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
        
    steps:
      - uses: actions/checkout@v4

      - name: Usar template o action reutilizable 
        uses: loteria-devops-resources/.github/actions/build/build-node-express@main
        with:
          node-version: ${{ matrix.node-version }}

      
      #- name: Use Node.js ${{ matrix.node-version }}
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: ${{ matrix.node-version }}
      #    cache: npm

      #- name: Install dependencies
      #  run: npm install

      #- name: Build project
      #  run: npm run build

      - name: Upload build artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_id }}
          path: dist/
          retention-days: 14
